### ISSUE TITLE
Micronaut 1.x document points to 2.0 solution

### ISSUE THREAD

**Issue by connorsadler** [micronaut-guides/micronaut-data-access-jpa-hibernate#11]
Firstly, thanks for the guide
I had some trouble following this yesterday because of the 1.x vs 2.0 transition
I can see the 1.x page now: https://guides.micronaut.io/1.x/micronaut-guides/micronaut-data-access-jpa-hibernate/guide/index.html
but the "completed example" link tells you to clone the 2.0 solution using
git clone https://github.com/micronaut-guides/micronaut-data-access-jpa-hibernate.git

Is there a way to point to a 1.x branch of the solution, please?

Cheers!

**Comment by sdelamo** [comment]
I've pushed.1.x branch: https://github.com/micronaut-guides/micronaut-data-access-jpa-hibernate/tree/1.x
