### ISSUE TITLE
Message: No bean of type [javax.persistence.EntityManager] exists

### ISSUE THREAD

**Issue by antimoroma** [micronaut-guides/micronaut-data-access-jpa-hibernate#7]
Using the example project, changing the directory containing the full application and the test, and updating the EmbeddedServer configuration to:
 server = ApplicationContext
                .build()
                 .packages("it.test")
                .run(EmbeddedServer.class); 

where "it.test" is a dir containing the entity 

Launching test we obtain the message 
Message: No bean of type [javax.persistence.EntityManager] exists

Complete project with failing code is in the complete project insiede this git repository
https://github.com/antimoroma/micronautGuidesTestJPA.git

**Comment by ilopmar** [comment]
This is not really related to the guide. I've upgraded it to use Micronaut Test and I can't really reproduce it. 
If the problem is still there please file an issue to Micronaut with and updated example.
